### ISSUE TITLE
Public URL of the trust store or URL to obtain public keys for verification with 3rd party app?

### ISSUE THREAD

**Issue by alexandermainz** [eu-digital-green-certificates/dgc-overview#35] opened 2021-06-17 15:01 UTC
Hello,

we would like to integrate the validation into our gastro software so that our staff does not need to use their personal smartphones with the "CovPassCheck" app.

Are there publicly available trust stores or is there a publicly available URI where one can obtain the public key to a given kid from a given issuer or something like a JWKS?

Being forced by government regulations to grant access to indoor venues only for tested or vaccinated people, we would prefer an easy way to check the official digital vaccination certificates of the guests.

Kind regards,
Alex

**Comment by daniel-eder** [comment] 2021-06-17 16:07
This is a duplicate of https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10

Please see https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10#issuecomment-862060966 and the following discussion.

**Closed by daniel-eder** 2021-06-17 16:07 UTC
Labels: general
